### ISSUE TITLE
the concrete meaning of obs

### ISSUE THREAD

**Issue by initial-h** [Farama-Foundation/MiniGrid#191]
Hi,
I'm running experiments on env RedBlueDoors with FullyObsWrapper and ImgObsWrapper.
There are three 2D arrays to present the features. I think the first array presents objects ID, the second one presents color ID and the third one presents agent's direction, it this correct? 
I find in RedBlueDoors, agent's direction and the status of door (open/closed) are all presented in the third array. I wonder is there a document that explains which array present what kind of features? 
Thanks!

**Comment by maximecb** [comment]
Hello.

The first array is the object type, the second is the color, and the third is a flag indicating for example if a door is open or not:
https://github.com/Farama-Foundation/gym-minigrid/blob/master/gym_minigrid/minigrid.py#L238

**Comment by initial-h** [comment]
Thank you very much! And the agent's direction is also presented in the third array right? I'm trying to find some logic that what kind of features are put together :)
