### ISSUE TITLE
[Bug Report] Error after updating to MiniGrid 1.2.0

### ISSUE THREAD

**Issue by ibagur** [Farama-Foundation/MiniGrid#232]
**Describe the bug**
I have upgraded to MiniGrid 1.2 (after updating to gym 0.26), but for some reason I cannot get it run. I have forked and cloned the repository so to download the code, but haven't performed any changes to it yet.

**Code example**

I try to run just the manual control script over a simple environment:

`./gym_minigrid/manual_control.py --env MiniGrid-Empty-5x5-v0`

I get the following errors:

**Traceback (most recent call last):
  File "./gym_minigrid/manual_control.py", line 102, in <module>
    env = gym.make(
  File "/Users/inigo/.local/share/virtualenvs/test-minigrid-ZLPD9hGZ/lib/python3.8/site-packages/gym/envs/registration.py", line 652, in make
    raise e
  File "/Users/inigo/.local/share/virtualenvs/test-minigrid-ZLPD9hGZ/lib/python3.8/site-packages/gym/envs/registration.py", line 640, in make
    env = env_creator(**_kwargs)
  File "/Users/inigo/Documents/cursos/Data Science/master_viu/work/test-minigrid/gym-minigrid/gym_minigrid/envs/empty.py", line 72, in __init__
    super().__init__(
TypeError: __init__() got an unexpected keyword argument 'new_step_api'

**System Info**
 * Describe how `gym-minigrid` was installed (pip, docker, source, ...)

- Forked the repo into my github, cloned it locally and just installed following the instructions:

`git clone https://github.com/ibagur/gym-minigrid.git`
`cd gym-minigrid`
`pip3 install -e .`

 * What OS/version of Linux you're using: MacOS 11.6
 * Python version : 3.8.6

**Additional context**

It seems something related to 'new_step_api' argument, but I cannot relate it to other issues that made reference to it

### Checklist

- [ X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/gym-minigrid/issues) in the repo (**required**)

**Comment by rodrigodelazcano** [comment]
Sorry about this @ibagur and thank you for notifying the bug. This PR https://github.com/Farama-Foundation/MiniGrid/pull/233 should fix this issue. The fix will be included in the next release.
