### ISSUE TITLE
[Question] How to access the BabyAI environments? 

### ISSUE THREAD

**Issue by JRC1995** [Farama-Foundation/Minigrid#283]
I can make gym environments for minigrid, but the document don't specify the registration ids for BabyAI environments. Trying "BabyAI-<level-name>-v0" doesn't seem to work (gives a NameNoutFound error).

**Comment by rodrigodelazcano** [comment]
Hi @JRC1995. We are making a release that includes the BabyAI environments soon (probably today). For now you can install the library from source:
```
git clone https://github.com/Farama-Foundation/Minigrid.git
cd Minigrid/
pip install -e.
````

Also, the documentation for the BabyAI environments will be updated in the near future. Currently, the name id's of the environments can be found here: https://github.com/Farama-Foundation/Minigrid/blob/268c56b691c330425544c4917db0a19746d83dc0/minigrid/__init__.py#L509

**Comment by rodrigodelazcano** [comment]
New release 2.1.0 with these changes has been made
