### ISSUE TITLE
Paper for Minigrid List of Publications

### ISSUE THREAD

**Issue by DrGlennn** [Farama-Foundation/Minigrid#290]
The following paper uses Minigrid (in particular the KeyCorridor environments) and you may like to include it in your list of Minigrid publications:

[Evolution Strategies for Sparse Reward Gridworld Environments](https://link.springer.com/chapter/10.1007/978-3-031-22695-3_19)

**Comment by pseudo-rnd-thoughts** [comment]
Thanks, could you make a PR including the link to the `docs/content/publications.md` file
https://github.com/Farama-Foundation/Minigrid/blob/master/docs/content/publications.md

**Comment by DrGlennn** [comment]
Thanks. We saw the update in the the list of publications at the link [https://github.com/Farama-Foundation/Minigrid/blob/master/docs/content/publications.md](url). However, the list of publications at [https://minigrid.farama.org/content/publications/](url) does not seem to have been updated. We note that two other publications have been included on the original link that also don't show on the second list of publications. Should we do a second pull-request there, or is there an issue with that second link being updated?

**Comment by pseudo-rnd-thoughts** [comment]
@DrGlennn We use version control on the website I believe such we don't show the master version of the project as this can be inconsistent with the latest released version.
I will investigate if we can some pages to equal to the project master and some the latest version

**Comment by DrGlennn** [comment]
@pseudo-rnd-thoughts Thanks for the explanation. That makes sense. I was just making sure that we'd done everything we were expected to do, and that we hadn't missed something. I'll close this issue, now.
