### ISSUE TITLE
[Question] Agent does not appear to show up in integer array representation of minigrid environment

### ISSUE THREAD

**Issue by DarthMalloc** [Farama-Foundation/Minigrid#301]
### Question

I am doing an RL experiment with the minigrid environment, so I ran a short test program to do a sanity check on the environment, in which I did a print of the integer array representation of the environment observation.
I posted a screenshot here which shows the observation array:

![Screenshot from 2023-01-27 21-53-04](https://user-images.githubusercontent.com/40067998/215240321-edfe9ec7-8014-4f50-99c2-2c4da6aaa0ce.png)

The file constants.py in the core folder shows that integer value for the agent within the encoded observation should be 10, but none of the tile tuples show that value in the first term. Is that supposed to be the case? It prevents the agent from getting exact information about its position within the environment.

**Comment by rodrigodelazcano** [comment]
Hi @DarthMalloc. The observations you are getting are correct. The grid representation is a partial observation of the agent's point of view (represented in light grey in this image https://github.com/Farama-Foundation/Minigrid/blob/master/figures/door-key-curriculum.gif). If you'd like to get a full representation of the grid you can wrap the environment with the `SymbolicObsWrapper`:
```python
from minigrid.wrappers import SymbolicObsWrapper
env = SymbolicObsWrapper(gym.make('EnvID'))
```

**Comment by pseudo-rnd-thoughts** [comment]
There is also a `FullObsWrapper`

**Comment by DarthMalloc** [comment]
Thank you very much for getting back to me so soon! Your response helps me a great deal! There is one last thing I was wondering - I noticed that the for the MiniGridEnv object class, there is a boolean parameter agent_pov, which is set to False by default. If this parameter is set to True, does it make the integer value for the agent appear within the observation array?
