### ISSUE TITLE
[Question] Any plan to support BabyAI bot ?

### ISSUE THREAD

**Issue by GilgameshD** [Farama-Foundation/Minigrid#308]
### Question

Thanks for bringing BabyAI into this repo. I wonder if there is any plan to support the bot that can generate expert demonstrations ([link of the script](https://github.com/mila-iqia/babyai/blob/master/babyai/bot.py)).

**Comment by pseudo-rnd-thoughts** [comment]
I haven't done much with BabyAI but I would add happy to add it if it is helpful to end users. @rodrigodelazcano Any thoughts? 
@GilgameshD Would you be interested in adding the file in a PR? It would need to include a copyright statement at the top of the file

**Comment by rodrigodelazcano** [comment]
I think this could be very valuable in order to generate datasets for Minari. 
I currently don't have time to work on it but if @GilgameshD you want to contribute to this I'll be happy to help with code review :)

**Comment by GilgameshD** [comment]
sounds good. I will try to make a PR when I finish it.

**Comment by Near32** [comment]
Hello!
I have updated the BabyAI bot to be operatable with both the legacy code and the Minigrid code, in case it can speed up full integration in here :
https://github.com/mila-iqia/babyai/pull/121
Good luck in the meantime!

**Comment by GilgameshD** [comment]
thanks @Near32 for providing a reference of the modification. I made the bot.py file compatible with Minigrid and wrote a simple example to run the bot on all BabyAI envs. Where do you think I should put the files? @pseudo-rnd-thoughts @rodrigodelazcano

**Comment by pseudo-rnd-thoughts** [comment]
@GilgameshD Would you be able to put it in `minigrid/utils/bot.py` along with several tests in `tests/utils/test_bot.py`
