### ISSUE TITLE
[Question] Is there a way to make the rendered environment no longer highlight the agent's field of view？

### ISSUE THREAD

**Issue by 1176358062** [Farama-Foundation/Minigrid#326]
### Question

Recently I am using object segmentation module to extract objects in images. However, the brightening of the agent's field of view hinders this behavior. Is there an easy way to do this?

**Comment by thesofakillers** [comment]
I am using the FullyObsWrapper but still get the field-of-view highlight when rendering.

**Comment by liruiluo** [comment]
> Hi @liruiluo, did you find a way of doing this? Could you share? Alternatively maybe @pseudo-rnd-thoughts could you comment? Thank you.

In an old version I modified the internal code base to implement this function, however, I have forgotten the implementation at that time
