### ISSUE TITLE
[Question] How to remove the white lines that divide the grid in the grid

### ISSUE THREAD

**Issue by 1176358062** [Farama-Foundation/Minigrid#335]
### Question

I'm using unsupervised learning to identify object locations, but the grid's dividing lines are getting in the way
Is there a way to get rid of this thin line?

**Comment by Roihn** [comment]
From my point of view, the easiest way is to comment out the following two lines in `minigrid/core/grid.py`
https://github.com/Farama-Foundation/Minigrid/blob/9203791c5ba489a4a6e6b6231851640f326a2ea4/minigrid/core/grid.py#L170-L171

These two lines draw the dividing lines over the whole grid. Hope this can help you.

**Comment by 1176358062** [comment]
> From my point of view, the easiest way is to comment out the following two lines in `minigrid/core/grid.py`
> 
> https://github.com/Farama-Foundation/Minigrid/blob/9203791c5ba489a4a6e6b6231851640f326a2ea4/minigrid/core/grid.py#L170-L171
> 
> These two lines draw the dividing lines over the whole grid. Hope this can help you.

Thanks. That works for me!
