### ISSUE TITLE
[Bug Report] Nothing shows up when rendering environments?

### ISSUE THREAD

**Issue by mikeg-123** [Farama-Foundation/Minigrid#338]
Hi everyone, sorry if this has been covered or deemed too basic but I'm really having an issue here. 

When I try to render an environment exactly as it's done in the example code [here](https://minigrid.farama.org/) I simply get a blank window. I'm using windows 11 and currently running python 3.10.10 through a VS code jupyter notebook. I have minigrid 2.2.0, gymnasium 0.26.3, and pygame 2.3.0. However I've tried meddling with different versions of all these things and no configuration seems to work for me, even using the older version of minigrid that runs with matplotlib instead of pygame just produces a blank plot. I am able to get the expected window when running manual_control.py but nothing when trying to use minigrid as intended outside of that. I'm also able to render base gym environments with pygame, eg the lunar landing environment. I'd very much appreciate any help anyone could give me, thanks.

**Comment by pseudo-rnd-thoughts** [comment]
Thanks for the issue, I will have a look into it

**Comment by BolunDai0216** [comment]
Can you try the following code

```python
import gymnasium as gym

env = gym.make("MiniGrid-Empty-5x5-v0", render_mode="human", screen_size=640)
observation, info = env.reset(seed=42)
for _ in range(1000):
    action = env.action_space.sample()  # User-defined policy function
    observation, reward, terminated, truncated, info = env.step(action)

    if terminated or truncated:
        observation, info = env.reset()
env.close()
```

and see if you see anything?

**Comment by mikeg-123** [comment]
@BolunDai0216 I had been using that exact code but without the screen_size parameter... I guess that makes all the difference because it's working as expected now. Thanks so much!

**Comment by BolunDai0216** [comment]
The issue is we have set a really small screen size as default, so it does appear, just not very noticeable. 

You can try removing the screen_size parameter, and if you pay attention there should be a really small window somewhere on your screen.

Thanks for pointing this issue out, we'll update the default screen size.
