### ISSUE TITLE
A potential problem for the latest version 2.2.0 with pygame. 

### ISSUE THREAD

**Issue by shuzechen** [Farama-Foundation/Minigrid#339]
I'm using the latest version 2.2.0. After I have cloned it from github, I ran the command `./minigrid/manual_control.py --env MiniGrid-Empty-8x8-v0`. And an error occurred 
```
File ".../gymnasium/envs/registration.py", line 642, in make
    env = env_creator(**_kwargs)
  File ".../minigrid/envs/empty.py", line 84, in __init__
    super().__init__(
TypeError: __init__() got an unexpected keyword argument 'screen_size'
```

**Comment by shuzechen** [comment]
Solved. I use `pip install minigrid` and install version 2.1.1.

**Comment by BolunDai0216** [comment]
Just to clarify, if you run `pip install minigrid` right now, is it still installing version 2.1.1?

**Comment by shuzechen** [comment]
No. It's now version 2.2.0.
