### ISSUE TITLE
[Question] Why is observation_space a Dict, and not a gym.spaces.space?

### ISSUE THREAD

**Issue by aldakata** [Farama-Foundation/Minigrid#353]
I am trying to port some code I used for gym to minigrid, and I have this compatibility issue. Why was this decision taken? Is there a deep, technical reason, or is it just how it is? Is there any common approach on how to fix this issue?

Thank you very much! (I would be happy to help work on this :))

P.S: Discord invite link has expired

**Comment by kir0ul** [comment]
Sorry, I don't have the answer to your question, but here is a link to Discord that should be working: https://discord.gg/UMsTVvBf

**Comment by pseudo-rnd-thoughts** [comment]
The observation includes an `image` of the environment, `agent_dir` is the agent direction and a `mission` is the goal of the agent. The mission can sometimes be ignored for some environment. 
The easiest way is to use a multi-input network for the agent, see the BabyAI paper for more information on the mission information

**Comment by BolunDai0216** [comment]
I will close this issue since there are no additional comments, please feel free to reopen it if anyone has any related questions.
