### ISSUE TITLE
Is there any function provided to change the location of the goal point?

### ISSUE THREAD

**Issue by GuochenZhou** [Farama-Foundation/Minigrid#357]
Excude me, is there any function provided by this library to change the location of the final point? As I need to set the location of the final point.

**Comment by pseudo-rnd-thoughts** [comment]
It doesn't look like it but it should be possible to iterate over all of the cells in the grid looking for `cell.type == "goal"`.

**Comment by BolunDai0216** [comment]
As @pseudo-rnd-thoughts mentioned, this is currently not a supported feature. 

You can set the target position in the environment by setting the value of `self.target_pos` in `_gen_grid()`.

I think you can do the same thing if you want to change the goal position dynamically (after the episode started). But there should be a few other things that you need to change, mostly related to `self.grid`.

**Comment by BolunDai0216** [comment]
I will close this issue since there are no additional responses, please feel free to reopen it if anyone has any related questions.
