### ISSUE TITLE
Paper to be included in the list of publications

### ISSUE THREAD

**Issue by alversafa** [Farama-Foundation/Minigrid#358]
Our [recent paper](https://arxiv.org/abs/2301.10119) makes use of the minigrid environment and we would like to include it in the [list of publications](https://minigrid.farama.org/content/publications/) if possible. 

What are the steps that we should follow? In the [readme file](https://github.com/Farama-Foundation/Minigrid), it states that we should start by raising an issue. There seems to be a closed issue around this #290, but just wanted to make sure that these are the steps to follow?

**Comment by pseudo-rnd-thoughts** [comment]
Hey, thanks for using minigrid in your paper. Could you make a PR to modify `docs/content/publications.md` with your paper information like https://github.com/Farama-Foundation/Minigrid/pull/223
