### ISSUE TITLE
[Question] Question title

### ISSUE THREAD

**Issue by BenSturgeon** [Farama-Foundation/Minigrid#367]
Hello! 

I am trying to set up a research and experimentation framework that tries to count the number of possible future states available in an environment given some state s. 

However, I am finding it difficult to explore deeper in the state tree without being able to save and load states. Is there any way around this, or a way to implement save and load functionality here? I find the difficulty comes when trying to pickle pygame surface objects as they are not serializable. 

Do you have any recommendations?

**Comment by pseudo-rnd-thoughts** [comment]
If you are not rendering the environment then you should be able to pickle the environment. 
Otherwise, we can look to fix that

**Comment by BenSturgeon** [comment]
You're right, when the environment isn't rendered then there is no problem.

However, it would be very helpful to be able to render the environment for visualisation purposes. 

How viable do you think it would be to get around the difficulties of serialising the pygame objects so that they could be copied, or finding some other way to copy them?

**Comment by pseudo-rnd-thoughts** [comment]
This is a pygame issue rather than a minigrid issue
As pygame uses c++ this might be more difficult

**Comment by BolunDai0216** [comment]
You may be able to get around it by saving the `self.grid` and storing the agent state.

**Comment by BolunDai0216** [comment]
Closed due to inactivity, feel free to reopen this issue if the problem persists
