### ISSUE TITLE
[Proposal] Wrapper / argument for legal actions

### ISSUE THREAD

**Issue by sparisi** [Farama-Foundation/Minigrid#369]
### Proposal 

Have a wrapper / flag that filter "illegal" actions. For instance, if there are no objects to pickup (like in MultiRoom) get rid of the pickup and drop actions. 

### Motivation

This is like Atari `full_action_space` argument. It would make debugging algorithms easier, because it's like having an easier version of the tasks. 

### Checklist

- [x] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/MiniGrid/issues) in the repo (**required**)

**Comment by pseudo-rnd-thoughts** [comment]
This is an interesting idea and I would be certainly interested in adding it. 
I'm not sure how to efficiently implement for every environment which would be the dream

**Comment by sparisi** [comment]
@pseudo-rnd-thoughts 
I have 2 ideas:
- Define the set of legal action for each "macro" MiniGrid env. In MultiRoom there will be no pick/place. In Crossing and Empty there will be no pick/place/toggle. Then map the actions accordingly.
- At the first grid generation, check for objects on the map. If no key/ball disable pick/place. 

I am not sure any of these will work on all env, since I haven't used all MiniGrid envs so far. For instance the latter may not work with GoToObject.
