### ISSUE TITLE
[Proposal] Decouple agent implementation and rendering from grid

### ISSUE THREAD

**Issue by tfederico** [Farama-Foundation/Minigrid#373]
### Proposal 

I think it would be a good idea to divide the implementation and rendering of the agent from the one of the grid

### Motivation

Currently, the grid and agents are both handled in [grid.py](https://github.com/Farama-Foundation/Minigrid/blob/master/minigrid/core/grid.py). Thus, if someone wants to change the appearance of the agent (e.g., from a triangle to a circle), they need to modify the function that renders the tile. This is not very modular imho, as if you change an agent you should just be able to change it without modify how a tile is rendered.

### Pitch

Divide the implementation of the tile rendering and the agent rendering, so that the agent can be changed in a modular fashion

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/MiniGrid/issues) in the repo (**required**)

**Comment by pseudo-rnd-thoughts** [comment]
Hey, yes, I think this is a good idea. I'm not sure how easy this will be, could you investigate and make a PR
The issue is that there are a number of improvements that I would be interested in doing however none of the environment's observations change is difficult

**Comment by BolunDai0216** [comment]
Closed due to inactivity, feel free to reopen this issue if the problem persists.
