### ISSUE TITLE
[Question] Question title

### ISSUE THREAD

**Issue by JustinS6626** [Farama-Foundation/Minigrid#375]
### Question

I have developed a custom environment that inherits from the `MiniGridEnv` base class, and in this environment, certain objects are placed in random locations. I have created some pre-generated grid layouts and saved them into files using pickle. Now I am trying to load one of the grid layouts from a file and initialize the environment from that layout. Would it be possible to see an example for how that might be done?

**Comment by BolunDai0216** [comment]
What format are the grid layouts saved as?

**Comment by BolunDai0216** [comment]
Feel free to reopen this.
