### ISSUE TITLE
[Question] DoorKey Locked Door Location Question

### ISSUE THREAD

**Issue by Yuning30** [Farama-Foundation/Minigrid#380]
I found that for the DoorKey environment, the locked door will not be placed on the lowest row where the goal is located. Is this designed on purpose or is this a bug?

Thank you for any response.

**Comment by BolunDai0216** [comment]
I think it is designed on purpose. From [here](https://github.com/Farama-Foundation/Minigrid/blob/546c040a9424f339b7ba69e911e4126cee216e64/minigrid/envs/doorkey.py#L94) you can see how to the position of the door is randomly sampled.

**Comment by pseudo-rnd-thoughts** [comment]
Looking at how the grid is generated yes https://github.com/Farama-Foundation/Minigrid/blob/546c040a9424f339b7ba69e911e4126cee216e64/minigrid/envs/doorkey.py#L75
Do you think this causes issues?
