### ISSUE TITLE
[Bug Report] RGBImgObsWrapper hardcodes `highlight` parameter

### ISSUE THREAD

**Issue by thesofakillers** [Farama-Foundation/Minigrid#382]
**Describe the bug**
When using `RGBImgObsWrapper` on an environment initialized with `highlight=False`, the images in the observation will still be rendered with `highlight=True`. This is because `True` highlighting is hardcoded in RGBImgObsWrapper, instead of respecting what is set by the environment being wrapped:

 https://github.com/Farama-Foundation/Minigrid/blob/546c040a9424f339b7ba69e911e4126cee216e64/minigrid/wrappers.py#L326

Instead of `highlight=True`, that should say `highlight=self.env.highlight` or equivalent. 

**Code example**
```python
from minigrid.wrappers import RGBImgObsWrapper
import gymnasium as gym
import matplotlib.pyplot as plt

env = gym.make("BabyAI-GoToLocal-v0", highlight=False)
env = RGBImgObsWrapper(env)

obs, _ = env.reset()
plt.imshow(obs['image'])
```
The plotted image will still show a highlight around the agent, despite us having specified not to highlight the agent's view.

**System Info**
Describe the characteristic of your environment:
 * Describe how `minigrid` was installed (pip, docker, source, ...)
 `pip install minigrid`
 * What OS/version of Linux you're using. Note that while we will accept PRs to improve Window's support, we do not officially support it.
MacOS Catalina 10.15.7
 * Python version
3.8.16

**Additional context**
Perhaps related: #162, #326 

### Checklist

- [x] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/MiniGrid/issues) in the repo (**required**)

**Comment by thesofakillers** [comment]
I can submit a PR with the proposed fix if this is welcome.

**Comment by pseudo-rnd-thoughts** [comment]
Thanks, yes that would be great. 
Does highlight default to True in environments?

**Comment by thesofakillers** [comment]
Yes highlight defaults to true in environments. 
See here: 
https://github.com/Farama-Foundation/Minigrid/blob/1eb0a7071749ad7f3ed3ffd0816a249bfe0bff2a/minigrid/minigrid_env.py#L45

I'll open a PR on Monday
