### ISSUE TITLE
[Question] Use of 'direction' in observation space?

### ISSUE THREAD

**Issue by kbkartik** [Farama-Foundation/Minigrid#385]
### Question

1) What is the use of 'direction' key in the observation dict? It hasn't been mentioned in the documentation. 

2) While training RL agents, do we use 'direction' variable in addition to 'image'?

Thanks!

**Comment by BolunDai0216** [comment]
The configuration of the agent depends on both its position and its direction. For example, if we use ">" to represent the agent, then

```
xxx   xxx  
x>x   x<x
xxx   xxx
```

represents the agent at the same position but in different directions. When training your RL agent, you can also incorporate the direction into your agent's state, there are multiple ways to construct your RL agent's state space, using the image is only one of them.
