### ISSUE TITLE
[Question] Getting total number of unique states

### ISSUE THREAD

**Issue by kbkartik** [Farama-Foundation/Minigrid#397]
### Question

1) How can I get the total number of unique low-dimensional states in an environment? For instance, in four rooms, there are 256 + 4 low dimensional states. However, I had to count this manually. Is it possible to get the unique states count automatically for each environment?

2) How can I get the total number of unique images in an environment?

**Comment by pseudo-rnd-thoughts** [comment]
Sadly no to both questions, there is no automatic way of doing this.
But it should be possible to write a depth first search to generate all of the unique states along with unique images
