### ISSUE TITLE
[Question] How to create vectorized envs for minigrid

### ISSUE THREAD

**Issue by kbkartik** [Farama-Foundation/Minigrid#398]
I would like to use vectorized envs to train SAC-Discrete. Is there an efficient way of implementing vectorized envs in minigrid?

**Comment by pseudo-rnd-thoughts** [comment]
Do you mean using the gymnasium Vector environments, `SyncVectorEnv` or `AsyncVectorEnv`?

**Comment by kbkartik** [comment]
Yes, do we use those wrappers for minigrid as well? I didn't find any resource pointing to vec envs in the documentation.

**Comment by pseudo-rnd-thoughts** [comment]
Yes, these should work for all environments in theory. Let us know if there is an issue
