### ISSUE TITLE
Python 3.11 support is missing from the README

### ISSUE THREAD

**Issue by timoklein** [Farama-Foundation/Minigrid#407]
Release 2.3.0 adds [Python 3.11](https://github.com/Farama-Foundation/Minigrid/releases/tag/v2.3.0) support but the README has not been updated and still states

> We support Python 3.7, 3.8, 3.9 and 3.10 on Linux and macOS.

It caused a short confusion for me when installing an environment with Python 3.11.

See https://github.com/Farama-Foundation/Minigrid/pull/408

**Comment by biplobsd** [comment]
Hello @timoklein Can you assign to me?
