### ISSUE TITLE
[Bug Report] Cannot run example code: TypeError: 'module' object is not callable

### ISSUE THREAD

**Issue by AsadJeewa** [Farama-Foundation/Minigrid#441]
**Describe the bug**
Cannot run example code: TypeError: 'module' object is not callable

**Code example**
https://minigrid.farama.org/content/training/

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/MiniGrid/issues) in the repo (**required**)

**Comment by AsadJeewa** [comment]
This file seems outdated: https://github.com/Farama-Foundation/Minigrid/blob/master/docs/content/training.md

**Comment by pseudo-rnd-thoughts** [comment]
What line exactly is causing errors?

**Comment by AsadJeewa** [comment]
When using the policy_kwargs in line 15: `model = PPO("CnnPolicy", env, policy_kwargs=policy_kwargs, verbose=1)`
```
return self.features_extractor_class(self.observation_space, **self.features_extractor_kwargs)
TypeError: 'module' object is not callable
```

**Comment by AsadJeewa** [comment]
`import minigrid
from minigrid.wrappers import ImgObsWrapper
from stable_baselines3 import PPO
import MinigridFeaturesExtractor
import gymnasium as gym

policy_kwargs = dict(
    features_extractor_class=MinigridFeaturesExtractor,
    features_extractor_kwargs=dict(features_dim=128),
)

env = gym.make("MiniGrid-Empty-16x16-v0", render_mode="rgb_array")
env = ImgObsWrapper(env)

model = PPO("CnnPolicy", env, policy_kwargs=policy_kwargs, verbose=1)
model.learn(2e5)`

**Comment by AsadJeewa** [comment]
Apologies I was importing from `MinigridFeaturesExtractor` incorectly. Changed it to `from MinigridFeaturesExtractor import MinigridFeaturesExtractor`
