### ISSUE TITLE
[Bug Report] Width/Height inverted in all non-square Minigrid environments with RGBImgObsWrapper

### ISSUE THREAD

**Issue by waymao** [Farama-Foundation/Minigrid#444]
**Describe the bug**
When the width and height of a custom minigrid environment are not the same, it causes the observation generated by `RGBImgObsWrapper` to have the width and height to be inverted. The shape of the obs in the obs space and the actual obs is thus inconsistent.

**Code example**
```
from minigrid.wrappers import RGBImgObsWrapper
import gymnasium

env = RGBImgObsWrapper(gymnasium.make("MiniGrid-BlockedUnlockPickup-v0")) # any non-square env will cause the error
print(env.observation_space)

obs, info = env.reset()
print(obs['image'].shape)

assert env.observation_space['image'].shape == obs['image'].shape
```

**System Info**
Describe the characteristic of your environment:
 * pip, 2.4.0 from github
 * Linux; Debian 12.
 * Python 3.11.9

**Additional context**
Possibly due to the way the grid renders itself (in the format of height/width/3), while the wrapper defines the observation space to be in width/height/3.

### Checklist

- [x] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/MiniGrid/issues) in the repo (**required**)

**Comment by pseudo-rnd-thoughts** [comment]
Thanks for reporting the issue, could you make a PR that fixes this issue?

**Comment by catanzaromj** [comment]
I just ran into this issue as well. Is there a PR open for this? If not, I can try.

**Comment by pseudo-rnd-thoughts** [comment]
@catanzaromj There isn't a PR, if you want to make one then go for it
