### ISSUE TITLE
[Bug Report] gymnasium.error.NameNotFound: Environment `BabyAI_GoToObjS6` doesn't exist.

### ISSUE THREAD

**Issue by crimsonstamb** [Farama-Foundation/Minigrid#452]
If you are submitting a bug report, please fill in the following details and use the tag [bug].

I'm trying to run the BabyAI bot and keep getting errors about none of the BabyAI environments existing. 
**Describe the bug**

**Code example**
from __future__ import annotations

import gymnasium as gym
import minigrid
from minigrid.utils.baby_ai_bot import BabyAIBot

#print(minigrid.__version__)
#print(gym.__version__)

env = gym.make("BabyAI_GoToObjS6-v1")

babyai_bot = BabyAIBot(env)

**Error:** 

raise error.NameNotFound(
gymnasium.error.NameNotFound: Environment `BabyAI_GoToObjS6` doesn't exist.

**System Info**
I have minigrid version 2.3.1 and gym 1.0.0. I have Python 3.11.0. I am working on a macOS Ventura version 13.7.

**Comment by pseudo-rnd-thoughts** [comment]
I don't think that Minigrid is compatible with gymnasium v1.0.0
@BolunDai0216

**Comment by BolunDai0216** [comment]
@pseudo-rnd-thoughts a PR is underway #453.

**Comment by Arseni1919** [comment]
Can you please make it compateable with gymnasium v1.0.0? is it a part of a plan at list? 😅
If I want to run minigrid I need an older version of gymnasium, right?

**Comment by pseudo-rnd-thoughts** [comment]
@Arseni1919 yes we are working on it, I imagine it will be fixed in a couple of days. 
In the meantime, use gymnasium v0.29.1
