### ISSUE TITLE
[Question] Observation for FullyObsWrapper

### ISSUE THREAD

**Issue by Martin36** [Farama-Foundation/Minigrid#460]
### Question

The observation of the environment is represented as a matrix of tiles, with the following values: "Each tile is encoded as a 3 dimensional tuple: (OBJECT_IDX, COLOR_IDX, STATE)". The STATE can take a value in the range [0,2]. However, when I add the FullyObsWrapper I get a value of 3 for the STATE for one of the tiles. What does this mean in this case (I did not find it in the documentation)?

**Comment by pseudo-rnd-thoughts** [comment]
could you provide an example script to see this for?

**Comment by Martin36** [comment]
Here is an example:

```python
import gymnasium as gym
import minigrid
from minigrid.wrappers import FullyObsWrapper

env = gym.make("BabyAI-GoToRedBall-v0")
env = FullyObsWrapper(env)

while True:
  obs, _ = env.reset()
  img = obs["image"]
  state = img[..., 2]
  if not (state <= 2).all():
    print("Invalid state")
```

If "Invalid state" prints, then there is at least one element ">= 2".

**Comment by pseudo-rnd-thoughts** [comment]
If you look at the implementation of `FullyObsWrapper` [here](https://github.com/Farama-Foundation/Minigrid/blob/e1560ba8e3be644dc4454aa485355c005f1e4602/minigrid/wrappers.py#L424) then it redefines the third element to the agent's direction which can be between 0 and 3 causing your error

**Comment by Martin36** [comment]
I see. How do we get the door states in the fully observable setting then? And maybe this modification should be in the documentation for the FullyObsWrapper.

**Comment by Martin36** [comment]
I got it now, that it is only the agent position grid cell that changes the value, all the others stay the same.
