### ISSUE TITLE
[Bug Report] Vectorizing wrappers

### ISSUE THREAD

**Issue by modanesh** [Farama-Foundation/Minigrid#461]
### Question

Using the Gymnasium vectorization, we can create a vector of envs with the following line:
```
import gymnasium as gym
import minigrid
envs = gym.make_vec("MiniGrid-DistShift1-v0", num_envs=3)
```

Using the Minigrid wrappers, we can apply different modifications to the evns:
```
import gymnasium as gym
import minigrid
from minigrid.wrappers import StochasticActionWrapper
envs = gym.make("MiniGrid-Empty-5x5-v0")
envs = StochasticActionWrapper(envs)
```

However, it throws an error when wrapping a vectorized env:
```
import gymnasium as gym
import minigrid
from minigrid.wrappers import StochasticActionWrapper
envs = gym.make_vec("MiniGrid-DistShift1-v0", num_envs=3)
envs = StochasticActionWrapper(envs)
```
The error is:
```
Traceback (most recent call last):
  line 9, in <module>
    envs = StochasticActionWrapper(envs)
  File "Minigrid/minigrid/wrappers.py", line 795, in __init__
    super().__init__(env)
  File "gymnasium/core.py", line 620, in __init__
    Wrapper.__init__(self, env)
  File "gymnasium/core.py", line 310, in __init__
    assert isinstance(env, Env)
AssertionError
```

**System Info**
 * Minigrid was installed from source, latest commit
 * Ubuntu 20.04
 * Python 3.8

### Checklist

- [x] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/MiniGrid/issues) in the repo (**required**)

**Comment by modanesh** [comment]
Thanks for the help. It works that way. But shouldn't it be compatible with `make_vec()`?

**Comment by pseudo-rnd-thoughts** [comment]
Looking at the docs again, https://gymnasium.farama.org/api/registry/#gymnasium.make_vec, you should be to do `gym.make_vec("MiniGrid-Empty-5x5-v0", wrappers=(StochasticActionWrapper,))`
