### ISSUE TITLE
Submissions/papers using MiniGrid?

### ISSUE THREAD

**Issue by maximecb** [Farama-Foundation/MiniGrid#59]
I'd like to compile a list of submissions and accepted papers using MiniGrid. If you've used MiniGrid in a paper on arxiv or published at a conference, or if you see papers in the wild using MiniGrid, please list them in comments :)

**Comment by konichuvak** [comment]
Goyal, Anirudh, et al. "InfoBot: Transfer and Exploration via the Information Bottleneck." arXiv preprint arXiv:1901.10902 (2019).

**Comment by konichuvak** [comment]
There are a few more papers citing the repo on Google Scholar:
https://scholar.google.com/scholar?cites=11957401431355930624&as_sdt=2005&sciodt=0,5&hl=en

**Comment by mfe7** [comment]
https://arxiv.org/abs/1908.09171

**Comment by paischer101** [comment]
Paischer, Fabian, et al. "History Compression via Language Models in Reinforcement Learning." Proceedings of the 39th International Conference on Machine Learning, PMLR 162:17156-17185, 2022, https://proceedings.mlr.press/v162/paischer22a.html
